style:
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    max: 3

complexity:
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: true

    
formatting:
  FinalNewline:
    active: false

performance:
  SpreadOperator:
    active: false

